name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  no-fmt-print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block fmt.Println
        run: |
          if git grep -n -E '(fmt|log)\.(Print|Printf|Println)\(' -- '*.go'; then
            echo "Delete your debug, damm it"
            exit 1
          fi

  build-linux:
    needs: no-fmt-print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwayland-dev \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev \
            libgl1-mesa-dev \
            libxkbcommon-dev \
            libegl1-mesa-dev \
            libdrm-dev \
            libgbm-dev

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build-windows:
    needs: no-fmt-print
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...